image: Ubuntu1804  # образ для сборки
stack: node 12  # окружение
branches:
  only:
    - main  # ветка main
cache: node_modules  # кеширование
install:
  - npm install  # команда установки зависимостей
build: off  # не используем webpack => нет сборки
test_script:
  - npm run lint && npm test  # скрипт сборки